server:
  port: 8082
spring:
  application:
    name:
      account-MS

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgres

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://isilo.db.elephantsql.com:5432/nxzkwlgn
    username: nxzkwlgn
    password: ss7dx_nBPqsqStfyo5A_6Ju4Z2E8KLgm


auth:
  checktoken: http://localhost:8081/auth/