CREATE SEQUENCE SEQ_TOKEN INCREMENT 6 MINVALUE 145 MAXVALUE 9999999999 START 145;

CREATE TABLE IF NOT EXISTS token(
    token_id INTEGER DEFAULT NEXTVAL('SEQ_TOKEN') PRIMARY KEY NOT NULL,
    token VARCHAR(300) UNIQUE NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    expiration TIMESTAMP NOT NULL
);